apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosip-mor.fullname" . }}
  labels:
    {{- include "mosip-mor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mosip-mor.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mosip-mor.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name | replace "_" "-" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80

