apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosip-mor.fullname" . }}
  labels:
    {{- include "mosip-mor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "mosip-mor.name" . }}

